name: Run every hour
on:
  schedule:
    - cron: "15 * * * *"
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TEAM_NAME: "${{ secrets.TEAM_NAME }}"
  CAPTAIN_NAME: ${{ secrets.CAPTAIN_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  PHONE: ${{ secrets.PHONE }}
  NUMBER_OF_PLAYERS: ${{ secrets.NUMBER_OF_PLAYERS }}
  TELEGRAM_NAME: ${{ secrets.TELEGRAM_NAME }}
jobs:
  run_every_hour:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python3 main.py
      - name: Save registered games
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add registered_games.json
          if git diff --staged --quiet; then
            echo "Нет изменений в registered_games.json"
          else
            git commit -m "Update registered_games.json"
            git push
          fi