name: Run every hour
on:
  push:
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TEAM_NAME: "${{ secrets.TEAM_NAME }}"
  CAPTAIN_NAME: ${{ secrets.CAPTAIN_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  PHONE: ${{ secrets.PHONE }}
  NUMBER_OF_PLAYERS: ${{ secrets.NUMBER_OF_PLAYERS }}
  TELEGRAM_NAME: ${{ secrets.TELEGRAM_NAME }}
jobs:
  run_every_hour:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python3 main.py